services:

  db_postgres:
    image: postgres:latest
    #platform: linux/amd64
    container_name: qlik-postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=POS
      - POSTGRES_USER=pos_user
      - POSTGRES_PASSWORD=pos-secret-pw
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./volumes/postgres:/opt/qlik

    ports:
      - 5432:5432
    networks:
      - nw-qlik

  db_mysql:
    image: mysql:latest
    #platform: linux/amd64
    container_name: qlik-mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql-pw
      #- MYSQL_DATA=/var/lib/minesql/data
    volumes:
      - msdata:/var/lib/mysql
      - ./volumes/mysql:/opt/qlik
      
    ports:
      - 3306:3306

    networks:
      - nw-qlik
    command:
    #  - mysql -h 127.0.0.1 -u root  -pmy-secret-pw  < /opt/qlik/ECommerce.sql

  kafka:
    image: bitnami/kafka:latest
    container_name: qlik-kafka
    hostname: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0 
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-server:9093 
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER 
    
    ports:
      - 9092:9092
    networks:
      - nw-qlik

  qlik_gw: 
    image: mjromper/q-gateway:latest

    platform: linux/amd64 
    container_name: qlik-gateway
    hostname: qlik-gateway
    
    #ports:
    
    environment:
      - OWNER_EMAIL=
      - MACHINEID=
      #- TENANT_NAMEREGION=tenantname.region
      - TENANT_NAMEREGION=rlindvig.eu
      - TENANT_DOMAIN=qlikcloud.com 
      #- QAA_URL="https://[TENANT_NAMEREGION].[TENANT_DOMAIN]/api/v1/automations/357cb3df-7a90-4c5c-9363-45a4ee68607a/actions/execute"
      #- QAA_EXEC_TOKEN="The QQAA token"
      #- QAA_TOKEN_HEADER_NAME="X-Execution-Token"

    volumes:
      - ./volumes/gateway:/opt/qlik/gw
      
    networks:
      - nw-qlik
      
    #entrypoint: /bin/bash
    
    depends_on:
      - db_postgres
      - db_mysql
      - kafka
      

# Named volumes (persisted on /var/lib/docker/volumes)
volumes:
  pgdata:
  msdata:

networks:
  nw-qlik:
    driver: bridge

#version: '3'

#services:
#  somename:
#    build:
#      context: ./app
#      dockerfile: Dockerfile
#      args:
#        some_variable_name: a_value
